# FROM tomosia/cakephp4-fpm:7.4
# 佈署給前端開實用的環境設定
FROM lqdt/cakephp3-php7-composer-xdebug


WORKDIR /var/www/html

ENV DEBCONF_NOWARNINGS yes

# 升級環境
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y \
	git \
	git-core \
	nano \
    zip \
	&& rm -rf /var/lib/apt/lists/*

# RUN docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd \
# && docker-php-ext-install \
#   intl \
#   mbstring \
#   pcntl \
#   pdo_mysql \
#   zip \
#   opcache \

# RUN docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd \
#   && docker-php-ext-install \
#   intl \
#   mbstring \
#   pcntl \
#   pdo_mysql \
#   zip \
#   opcache \
# 　&& rm -rf /var/lib/apt/lists/*  

# 安裝CAKE所需的相關基本外掛
# RUN apt-get -y update \
# && apt-get install -y libicu-dev \
# && docker-php-ext-configure intl \
# && docker-php-ext-install intl \
# && docker-php-ext-configure pdo_mysql \
# && docker-php-ext-install pdo_mysql \
# && rm -rf /var/lib/apt/lists/*  

#install composer
# RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
# RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
# RUN php composer-setup.php
# RUN php -r "unlink('composer-setup.php');"
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
# RUN mv composer.phar /usr/local/bin/composer

WORKDIR /var/www/html
COPY . /var/www/html

